// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Comment: typeof import('./src/components/comment.vue')['default']
    Content: typeof import('./src/components/content.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBotton: typeof import('element-plus/es')['ElBotton']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Loading: typeof import('./src/components/loading.vue')['default']
    Message: typeof import('./src/components/message.vue')['default']
    Nav: typeof import('./src/components/nav.vue')['default']
    Report: typeof import('./src/components/report.vue')['default']
    ReportUser: typeof import('./src/components/reportUser.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollContentBox: typeof import('./src/components/scrollContentBox.vue')['default']
    Search: typeof import('./src/components/search.vue')['default']
    SVGIcon: typeof import('./src/components/SVGIcon.vue')['default']
    Topic: typeof import('./src/components/topic.vue')['default']
    User: typeof import('./src/components/user.vue')['default']
    UserCard: typeof import('./src/components/userCard.vue')['default']
  }
}
